
vhssl  {
  keyFile                 /etc/letsencrypt/live/srv691444.hstgr.cloud/privkey.pem
  certFile                /etc/letsencrypt/live/srv691444.hstgr.cloud/fullchain.pem
  certChain               1
  sslProtocol             24
  enableECDHE             1
}
