
extprocessor astroval_proxy {
  type                    proxy
  address                 127.0.0.1:18090
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context / {
  type                    proxy
  handler                 astroval_proxy
  addDefaultCharset       off
}
