const fs = require('fs');
const path = require('path');

// Complete Pantheon of 14 Grimoiric Operative Works
const allOperativeWorks = [
  {
    id: "love",
    glyph: "❤️",
    title: "1. Love & Erotic Attraction",
    name: "Al-Hubb & Al-'Ishq (المحبة والعشق)",
    category: "Jalb",
    viability: 28,
    viabilityVerdict: "PROSCRIBED for Naive Attraction (28%) • Hazardous Inversion Warning",
    gaugeColor: "#ec4899",
    astrologicalEngine: "Venus Stationary-Retrograde at 08°29′ Scorpio (Detriment, frozen speed -0.017°/day). Square Mars in Leo (5°13′). Moon in Cancer trines Venus (4°21′).",
    classicalProhibition: "Picatrix Bk. II Ch. 10 & Agrippa Bk. II Ch. 32 strictly proscribe love talismans when Venus is in Scorpio or retrograde. Casting naive attraction spells under this sky results in suffocating jealousy, paranoid obsession, and mutual contempt.",
    prescribedAction: "Reserved only for inward erotic shadow integration, reclaiming sensual self-respect, and healing sexual betrayal.",
    authorities: ["Picatrix (Ghayat al-Hakim) Bk. II Ch. 10", "Agrippa De Occulta Philosophia Bk. II Ch. 32", "Shams al-Ma'arif (Bab al-Mahabbah)", "PGM IV. 2967-3006"],
    altarMateria: "Tarnished copper, rose quartz, dark red candles, unhandled iron athame.",
    fumigation: "Myrrh resin, storax, dried red rose petals, crushed coriander seeds.",
    protocolName: "Protocol 1: Underworld Aphrodite Shadow Alignment (PGM IV. 2967)",
    verse: "يَا وَدُودُ يَا رَحِيمُ (Withheld from external binding) — 'Aphrodite Melaina, restore unto my vessel its stolen flame.'",
    formula: "Do NOT cast on another person. Anoint heart and wrists with pomegranate water over storax smoke. Meditate on emotional self-sovereignty.",
    effects: {
      psychological: "Purges shame, guilt, and emotional desperation; establishes solid relational self-worth.",
      relational: "Repels narcissistic manipulators who feed on unearned empathy.",
      somatic: "Relieves heart palpitations and tension in the thoracic diaphragm.",
      astral: "Cauterizes auric leeches hooked into the sacral chakra.",
      karmic: "Clears lineage patterns of codependent romantic martyrdom."
    },
    reversal: "If unwanted obsession is provoked: wash with rue and salt water, light white candle, recite Surah Al-Falaq."
  },
  {
    id: "severance",
    glyph: "✂️",
    title: "2. Cord-Cutting & Severance",
    name: "Al-Tafriq & Al-Faskh (التفريق وفسخ العهود)",
    category: "Tafriq",
    viability: 95,
    viabilityVerdict: "SUPREME PEAK (95%) — Irrevocable Severance & Soul-Tie Dissolution",
    gaugeColor: "#f43f5e",
    astrologicalEngine: "Stationary Venus in Scorpio receiving applying trine from Domicile Moon in Cancer (4°21′); Mars in Leo opposite Pluto (0°10′).",
    classicalProhibition: "Do not perform cord-cutting with hesitation or nostalgic regret; the iron cut must be absolute and final.",
    prescribedAction: "Severing toxic ex-partners, narcissistic trauma bonds, parasitic friendships, and unwanted psychic links.",
    authorities: ["Shams al-Ma'arif al-Kubra (Bab al-Tafriq)", "Picatrix Bk. IV Ch. 7", "PGM XXXVI. 1-34"],
    altarMateria: "Black wool cord with 7 knots, unhandled iron boline or athame, lead plate, two black candles.",
    fumigation: "Myrrh, galbanum, dried pomegranate peel, sulfur, powdered wormwood.",
    protocolName: "Protocol 2: The Seven-Knot Cleaving Rite (Tafriq al-Batil)",
    verse: "أَوَلَمْ يَرَ الَّذِينَ كَفَرُوا أَنَّ السَّمَاوَاتِ وَالْأَرْضَ كَانَتَا رَتْقًا فَفَتَقْنَاهُمَا (Surah 21:30)",
    formula: "Tie 7 knots in black cord. Pass through sulfur-myrrh smoke. Slice each knot with consecrated iron shouting: 'FA-FATAQNĀHUMĀ!' Burn severed remnants to ash; bury facing West.",
    effects: {
      psychological: "Immediate cessation of obsessive mental replays; emotional detachment and calm clarity.",
      relational: "Target experiences abrupt disconnect and usually attempts one last desperate contact (which must be ignored).",
      somatic: "Instant physical lightness; tension leaves the solar plexus and throat.",
      astral: "Astral threads linking subtle bodies are permanently severed and cauterized.",
      karmic: "Fulfills and closes out toxic karmic contracts permanently."
    },
    reversal: "Cannot be undone easily. If mistakenly severed, reconciliation requires new voluntary election months later."
  },
  {
    id: "binding",
    glyph: "🔒",
    title: "3. Binding & Tongue-Tying",
    name: "Al-'Aqd & Katadesmoi (العقد والربط وعقد الألسنة)",
    category: "Aqd",
    viability: 99,
    viabilityVerdict: "SUPREME OPTIMAL PEAK (99%) — Maximum Astrological Potency in Years",
    gaugeColor: "#94a3b8",
    astrologicalEngine: "Saturn physically culminating at +75.25° NW near Zenith overhead Jakarta; Saturday day ruler opposite Sun; Moon at Mansion 8/9 cusp.",
    classicalProhibition: "Never bind an innocent soul or act out of petty spite; unjust bindings rebound directly upon the operator's joints and finances.",
    prescribedAction: "Silencing slanderers ('Aqd al-Lisan), freezing courtroom adversaries, shutting mouths of perjurers, binding hostile entities.",
    authorities: ["Shams al-Ma'arif (Bab 'Aqd al-Alsinah)", "PGM V. 304-447 (Lead Defixio of Kronos)", "Picatrix Bk. II Ch. 10"],
    altarMateria: "Sheet lead (3x3 in), cold forged iron padlock with key, iron engraving stylus, black waxed cord.",
    fumigation: "Myrrh resin, cypress needles, assafoetida (Hiltit), bruised juniper berries, black poppy seed.",
    protocolName: "Protocol 3: The Cold Lead Tongue-Binding ('Aqd al-Lisan)",
    verse: "صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ (Deaf, dumb, and blind; they cannot return) + 3x3 Magic Square of Saturn (Wafq Zuhal)",
    formula: "Engrave 3x3 Saturn square on lead. Roll tightly around iron padlock shackle. Click lock shut: 'As Kronos sealeth the tomb, so is thy tongue locked.' Throw key in river; bury padlock under stone.",
    effects: {
      psychological: "Target experiences sudden mental fatigue, severe apathy, and amnesia regarding their hostile agenda.",
      relational: "Adversary stutters, contradicts themselves in public, or drops lawsuits abruptly.",
      somatic: "Adversary feels unexplained throat constriction and heavy limb fatigue when trying to speak malice.",
      astral: "Target's hostile thought-forms are trapped in the lead-iron lattice and grounded into earth.",
      karmic: "Imposes cosmic stasis upon malicious actions until divine justice arbitrates."
    },
    reversal: "Unlock padlock with original key while reciting Psalm 146:7 & Surah 94. If key lost, boil 7 iron keys in rue water."
  },
  {
    id: "cleansing",
    glyph: "🌊",
    title: "4. Cleansing & Uncrossing",
    name: "Al-Taharah & Lustratio (الطهارة والاستنزال وحل المعقود)",
    category: "Tahsin",
    viability: 96,
    viabilityVerdict: "SUPREME PURGATION (96%) — Domicile Moon & Sirius Catharsis",
    gaugeColor: "#38bdf8",
    astrologicalEngine: "Moon in Home Domicile in Cancer (12°50′) in 12th House conjunct Royal Star Sirius (14°27′); Waning 48.1% (Krishna Ashtami); Mercury trine Fomalhaut (0°01′).",
    classicalProhibition: "Do not cleanse with hot, fiery martial spices when seeking emotional restoration; use cooling lunar botanicals.",
    prescribedAction: "Dissolving Evil Eye (Al-'Ayn), breaking generational curses (Ibtal al-Sihr), lustral baths, fumigating residential space.",
    authorities: ["Shams al-Ma'arif (Bab al-Ibtal wa-l-Fakk)", "Agrippa Bk. I Ch. 43 (Lustral Waters)", "PGM XII & VII", "Corpus Hermeticum"],
    altarMateria: "Silver or glass bowl, 7 liters of rainwater/springwater, 1 cup unrefined coarse sea salt, white candles.",
    fumigation: "Frankincense tears (Luban Dhakar), white sandalwood, camphor, lavender, dried bay leaves.",
    protocolName: "Protocol 4: The Seven-Herb Celestial Lustratio (Ghusl al-Ibtal)",
    verse: "Ayat al-Kursi (2:255) + Surahs Al-Falaq & An-Nas (Recited 33 times with breath blown over water)",
    formula: "Steep Rue, Hyssop, Camphor, Sandalwood, Frankincense, Lavender, and Rosewater with sea salt. Pour from crown of head down entire body. Air-dry on skin.",
    effects: {
      psychological: "Immediate dissipation of chronic brain fog, irrational anxiety, and dread; radiant mental lucidity.",
      relational: "Parasitic, envious acquaintances feel uneasy and quietly drift away without drama.",
      somatic: "Release of tension in neck, trapezius, and lower back where negative cords attach; restorative sleep.",
      astral: "Auric tears repaired; shimmering silver-blue boundary reconstituted around subtle body.",
      karmic: "Neutralizes inherited family curses and clears astral miasma."
    },
    reversal: "Cleansing has zero negative recoil; if mild temporary nausea occurs, it is a detox Herxheimer response."
  },
  {
    id: "protection",
    glyph: "🛡️",
    title: "5. Protection & Boundary Armor",
    name: "Al-Tahsin & Hifz (التحصين والحفظ والحروز القاطعة)",
    category: "Tahsin",
    viability: 98,
    viabilityVerdict: "INVINCIBLE FORTIFICATION (98%) — Kinetic Mirror Counter-Strike Shield",
    gaugeColor: "#f59e0b",
    astrologicalEngine: "Mars in Leo (03°16′) in 1st house in exact 0°10′ opposition to Pluto in Aquarius (03°06′) in 7th house; Saturn at Zenith anchors four corners; Royal Stars Fomalhaut & Aldebaran form archangelic canopy.",
    classicalProhibition: "Never erect an impenetrable ward around yourself before performing thorough cleansing; otherwise, existing internal parasites will be trapped inside.",
    prescribedAction: "Apotropaic mirror amulets, reflecting attacks tenfold, 4-corner iron boundary stakes, Archangelic circle casting.",
    authorities: ["Shams al-Ma'arif (Bab al-Tahsin bi-l-Awfaq)", "Agrippa Bk. II Ch. 22", "Picatrix Bk. II Ch. 7", "PGM VII. 969-972"],
    altarMateria: "4 large forged iron masonry nails, 4 raw black tourmaline stones, polished steel mirror, red silk pouch.",
    fumigation: "Dragon's blood resin, black peppercorns, dried chili, frankincense, tobacco leaf.",
    protocolName: "Protocol 5: The 4-Corner Iron Stake Boundary Ward (Tahriz al-Arba'ah)",
    verse: "يَا عَزِيزُ يَا قَهَّارُ يَا قَوِيُّ يَا مَتِينُ يَا مُنْتَقِمُ (5 Divine Names of Subjugation) + 5x5 Wafq of Mars",
    formula: "Anoint 4 iron stakes with black pepper oil. Drive one nail with black tourmaline into North corner, proceed clockwise to East, South, West. Stamp foot in center: 'THE BORDER IS SEALED. IT IS FINISHED.'",
    effects: {
      psychological: "Unshakeable calmness, sovereign authority, absolute immunity to gaslighting, intimidation, and panic.",
      relational: "Hostile competitors find their aggressive maneuvers backfiring immediately onto their own reputations and finances.",
      somatic: "Elevated adrenal vitality; elimination of mysterious fatigue caused by psychic draining.",
      astral: "A blinding aura of ruby-red and gold deflects etheric darts, jealousy, and evil eye back to origin.",
      karmic: "Fixes the practitioner's sovereign destiny upon its true orbit."
    },
    reversal: "To dismantle: pull iron nails in counter-clockwise order starting from West, submerge in salt brine, thank the guardians."
  },
  {
    id: "war",
    glyph: "⚔️",
    title: "6. War & Dismantling Oppressors",
    name: "Al-Harb & Victoria (الحرب والغلبة وكسر الحصون)",
    category: "Tafriq",
    viability: 97,
    viabilityVerdict: "MAXIMUM COMBAT INTENSITY (97%) — Shattering Oppressive Fortresses",
    gaugeColor: "#dc2626",
    astrologicalEngine: "Mars at 03°16′ Leo in 1st house in exact 0°10′ opposition to Pluto at 03°06′ Aquarius in 7th house. Mars trine Neptune (0°29′), square Mercury (0°57′).",
    classicalProhibition: "Only deploy against real, documented systemic abuse or malicious aggressors. Initiating unprovoked aggressive warfare results in severe martial backlash.",
    prescribedAction: "Neutralizing predatory corporate or institutional oppressors, breaking malicious legal blockades, defending against spiritual warfare.",
    authorities: ["Picatrix Bk. II Ch. 7 (Talismans of Mars)", "Shams al-Ma'arif (Bab al-Awfaq li-l-Qahr)", "Agrippa Bk. II Ch. 22", "PGM IV. 2241-2358"],
    altarMateria: "Iron blade, red jasper, copper-iron talismanic plate, red candle, martial oil.",
    fumigation: "Dragon's blood, red chili pods, black pepper, sulfur, dried mustard seed.",
    protocolName: "Protocol 6: The Martial Shattering Blade (Ibtal al-Hisn)",
    verse: "وَقُلْ جَاءَ الْحَقُّ وَزَهَقَ الْبَاطِلُ ۚ إِنَّ الْبَاطِلَ كَانَ زَهُوقًا (Surah 17:81) + 5x5 Wafq of Mars",
    formula: "Engrave 5x5 Mars square on iron sheet while Mars is rising. Wrap in red silk with 5 barley grains. Recite 65 times 'Yā Qahhār Yā Matīn'. Strike iron blade into wooden block facing adversary.",
    effects: {
      psychological: "Unshakable martial courage; complete elimination of cowardice, hesitation, and victim mentality.",
      relational: "Adversary's coalition disintegrates; oppressive institutional managers are reassigned, resign, or suffer exposure.",
      somatic: "Surge in physical strength, muscular endurance, and cellular regeneration.",
      astral: "Demolishes the etheric energy reservoirs and talismans of hostile magical lodges or attackers.",
      karmic: "Executes divine cosmic rebalancing against entrenched tyranny."
    },
    reversal: "Extinguish martial fire by wrapping iron in white linen, anointing with olive oil, reciting verses of peace (Surah 36:58)."
  },
  {
    id: "pacification",
    glyph: "🕊️",
    title: "7. Pacification & Quelling Wrath",
    name: "Al-Silm & Thymokatochon (تسكين الغضب وعقد ألسنة الحكام)",
    category: "Aqd",
    viability: 92,
    viabilityVerdict: "HIGHLY EFFICACIOUS (92%) — Quelling Fury of Superiors & Foes",
    gaugeColor: "#a7f3d0",
    astrologicalEngine: "Moon at 12°50′ Cancer entering Lunar Mansion 9 (Al-Tarf / The Eye), applying trine to Venus in Scorpio; Moon in Domicile cools the Fixed T-Square.",
    classicalProhibition: "Do not attempt pacification while harboring active contempt; your own heart must be cool as water for the spell to transfer.",
    prescribedAction: "Calming an enraged boss, disarming hostile judges, settling volatile family feuds, quelling domestic anger.",
    authorities: ["PGM XII. 161-189 (Thymokatochon)", "Picatrix Bk. I Ch. 5 (Mansion 9 Al-Tarf)", "Shams al-Ma'arif (Bab Taskin al-Ghadab)"],
    altarMateria: "Cup of pure spring water, white pearl or silver coin, white candle, blue silk.",
    fumigation: "White sandalwood, camphor, lavender flowers, mastic resin.",
    protocolName: "Protocol 7: The Thymokatochon Water Offering (PGM XII. 161)",
    verse: "وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ (Surah 3:134) — 'I bind the bile; I extinguish the coal; I cool the boiling blood.'",
    formula: "Drop silver coin into spring water. Recite PGM formula 7 times. Sprinkle water silently upon threshold, doorknob, or legal documents.",
    effects: {
      psychological: "Instant cooling of internal frustration and rage; deep serenity and diplomatic poise.",
      relational: "Enraged superior or adversary suddenly stammers, softens their tone, and seeks peaceful resolution.",
      somatic: "Lowers blood pressure, relaxes constricted neck blood vessels, relieves bile/acid reflux.",
      astral: "Absorbs and grounds the red energetic spikes of rage into the cool lunar water element.",
      karmic: "Prevents karmic entanglements born of rash, wrathful speech and violence."
    },
    reversal: "Naturally subsides once the confrontation passes; no counter-rite required."
  },
  {
    id: "knowledge",
    glyph: "👁️",
    title: "8. Occult Knowledge & Prophecy",
    name: "Al-Kashf & Gnosis (الكشف والاستنزال واستنطاق الأرواح)",
    category: "Kashf",
    viability: 99,
    viabilityVerdict: "SUPREME CLARITY (99%) — Exact Trine to Royal Star Fomalhaut (0°01′)",
    gaugeColor: "#2dd4bf",
    astrologicalEngine: "Mercury at 04°13′ Scorpio in EXACT Trine (0°01′ orb!) to Royal Star Fomalhaut (04°15′ Pisces). Moon in Ardra Nakshatra.",
    classicalProhibition: "Never utilize revelation for petty voyeurism or manipulating others; spiritual blindness will result.",
    prescribedAction: "Deciphering cryptic grimoires, water scrying, diagnosing spiritual root causes, direct communion with Holy Guardian Angel.",
    authorities: ["Shams al-Ma'arif (Bab Kashf al-Asrar)", "Agrippa Bk. II Ch. 47 on Fomalhaut", "Picatrix Bk. III Ch. 6", "PGM XIII"],
    altarMateria: "Flawless clear quartz sphere or black scrying mirror, white candle, consecrated parchment, saffron ink.",
    fumigation: "Frankincense, mastic resin, bay laurel leaf, benzoin, star anise.",
    protocolName: "Protocol 8: The Rite of the Unveiled Eye (Kashf al-Ghayb)",
    verse: "يَا عَلِيمُ يَا حَكِيمُ يَا هَادِي يَا خَبِيرُ (Recited 100 times) + Stele of Hermes-Thoth (PGM)",
    formula: "Face Southwest toward Fomalhaut (+45° elevation). Light white candle over mastic smoke. Gaze into quartz crystal for 15 minutes; record all visions verbatim.",
    effects: {
      psychological: "Piercing deductive clarity; rapid synthesis of complex data; lightning-flash epiphanies.",
      relational: "Ability to instantly see through deceit, flattery, and hidden agendas in associates.",
      somatic: "Sensation of cool vibration at the forehead (ajna center); enhanced visual acuity.",
      astral: "Third eye membrane cleansed of astral debris; direct channel opened to Archangel Gabriel.",
      karmic: "Aligns the mortal mind with eternal primordial wisdom (Gnosis)."
    },
    reversal: "To close the eye: wash face with cold water, blow out candle, touch salt, declare: 'The veil is drawn.'"
  },
  {
    id: "wealth",
    glyph: "💰",
    title: "9. Wealth & Commercial Abundance",
    name: "Al-Rizq & Al-Jalb (جلب الرزق والتجارة والبركة)",
    category: "Jalb",
    viability: 68,
    viabilityVerdict: "MODERATE / STRATEGIC (68%) — Focus on Long-Term Asset Structure",
    gaugeColor: "#eab308",
    astrologicalEngine: "Jupiter in Leo (20°05′) in 1st house co-present with Mars, trine Midheaven (25°40′ Aries); Venus Rx in Scorpio warns against luxury speculation.",
    classicalProhibition: "Avoid get-rich-quick gambles, speculative crypto trading, or reckless borrowing while Venus is retrograde.",
    prescribedAction: "Auditing accounts, structuring long-term business covenants, establishing disciplined financial foundations, clearing debt.",
    authorities: ["Picatrix Bk. II Ch. 6 (Talismans of Jupiter)", "Shams al-Ma'arif (Bab Jalb al-Arzaq)", "Agrippa Bk. II Ch. 22", "Key of Solomon"],
    altarMateria: "Gold or polished brass disc, cedarwood box, green candle, consecrated ink with saffron and musk.",
    fumigation: "Cedar chips, nutmeg, cloves, benzoin resin, dried mint leaves.",
    protocolName: "Protocol 9: The 4x4 Jupiterian Covenant (Wafq al-Mushtari)",
    verse: "إِنَّ هَٰذَا لَرِزْقُنَا مَا لَهُ مِن نَّفَادٍ (Surah 38:54) + 4x4 Magic Square of Jupiter (Base 34, Total 136)",
    formula: "Write 4x4 Jupiter square on parchment with saffron ink. Anoint corners with cedar oil. Recite 100 times 'Yā Bāsitu Yā Ghaniyyu Yā Mughnī'. Place inside cash box or ledger.",
    effects: {
      psychological: "Eradicates chronic poverty terror, scarcity paranoia, and financial imposter syndrome.",
      relational: "Attracts high-value, honorable business partners and reliable clients who honor payment terms.",
      somatic: "Releases subconscious hoarding tension in gut and jaw.",
      astral: "Clears etheric blockage around the solar plexus chakra; establishes magnetic flow of resources.",
      karmic: "Transforms commercial activity into a vehicle for honorable stewardship and generosity."
    },
    reversal: "If greed or hubris arises: donate 10% of proceeds to the poor without public acknowledgment to ground the circuit."
  },
  {
    id: "healing",
    glyph: "🩺",
    title: "10. Healing & Somatic Renewal",
    name: "Al-Shifa' & Hygieia (الشفاء واسترداد العافية)",
    category: "Tahsin",
    viability: 88,
    viabilityVerdict: "HIGHLY RESTORATIVE (88%) — Domicile Moon Conjunct Sirius",
    gaugeColor: "#10b981",
    astrologicalEngine: "Moon in Domicile Cancer conjunct Sirius (The Great Healer); Sun in Libra trine Royal Star Aldebaran (0°21′); Mars trine Neptune (0°29′).",
    classicalProhibition: "Do not perform surgery on body parts ruled by Cancer (stomach, breasts, lymphatic system) while the Moon occupies Cancer.",
    prescribedAction: "Cellular rejuvenation, nervous system resetting, herbal restorative broths, water sound therapy, recovering from burnout.",
    authorities: ["Picatrix Bk. III Ch. 12", "Agrippa Bk. I Ch. 44", "Shams al-Ma'arif (Bab al-Shifa')", "PGM XIII. 230-245"],
    altarMateria: "Silver bowl of clean water, green jade or carnelian stone, white beeswax candle, linen cloth.",
    fumigation: "Mastic, dried eucalyptus, peppermint, frankincense, lemon balm.",
    protocolName: "Protocol 10: The Lustral Sirius Salve (Shifa' bi-Nūr al-Shi'ra)",
    verse: "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ (Surah 26:80) + 'Yā Shāfī Yā Mu'āfī Yā Kāfī'",
    formula: "Hold carnelian stone in water under the light of Sirius. Recite 66 times the Verse of Healing. Drink half the water; use remaining to bathe affected limb or forehead.",
    effects: {
      psychological: "Profound soothing of somatic trauma memories; nervous system shifts from fight-or-flight to rest-and-digest.",
      relational: "Dissolves hypervigilance; restores ability to receive care and comfort from loved ones.",
      somatic: "Accelerated cellular repair, reduced systemic inflammation, optimal deep sleep cycles.",
      astral: "Cleanses murky grey etheric sludge from the vital aura; infuses silvery-white prana.",
      karmic: "Clears generational illness scripts and somatic trauma inherency."
    },
    reversal: "Purely restorative; zero backfire possibility."
  },
  {
    id: "sovereignty",
    glyph: "👑",
    title: "11. Sovereignty, Honor & Authority",
    name: "Al-Jah & Basileia (الجاه والهيبة والقبول عند الملوك)",
    category: "Jalb",
    viability: 82,
    viabilityVerdict: "GRAVITATIONAL COMMAND (82%) — Mars-Jupiter in Sovereign Leo 1st House",
    gaugeColor: "#f97316",
    astrologicalEngine: "Mars and Jupiter in royal sign of Leo in 1st House; Sun trine Royal Star of the East Aldebaran (0°21′); Saturn at Zenith.",
    classicalProhibition: "Beware of tyrannical arrogance; pride before superiors while Sun is in Fall in Libra causes swift public humiliation.",
    prescribedAction: "Executive command presence, courtroom testimony authority, job interviews, demanding fair compensation, inspiring public trust.",
    authorities: ["Picatrix Bk. II Ch. 8 (Talismans of the Sun)", "Shams al-Ma'arif (Bab al-Haybah)", "Agrippa Bk. II Ch. 22", "PGM IV. 1596-1715"],
    altarMateria: "Pure gold or sun-polished brass coin, bay laurel leaves, golden-yellow candle, tiger's eye stone.",
    fumigation: "Pure frankincense tears, bay laurel leaves, dried amber resin, cinnamon bark.",
    protocolName: "Protocol 11: The Crown of Aldebaran (Haybat al-Muluk)",
    verse: "يَا مَالِكُ يَا قُدُّوسُ يَا سَلَامُ يَا مُؤْمِنُ يَا مُهَيْمِنُ (Divine Names of Majestic Presence)",
    formula: "Anoint forehead with oil of cinnamon and frankincense. Carry gold coin wrapped in yellow silk on right chest. Recite 70 times 'Yā 'Azīzu Dhū al-Intiqām'. Walk with spine erect.",
    effects: {
      psychological: "Unshakable poise, magnetic executive voice, complete eradication of stage fright or intimidation.",
      relational: "Superiors and subordinates naturally defer, listen attentively, and grant requests without resistance.",
      somatic: "Expansion of chest and respiratory capacity; grounded, authoritative physical posture.",
      astral: "Radiates a blazing golden-amber corona around the head that commands instinctual deference.",
      karmic: "Ascends the soul into its rightful royal leadership vocation."
    },
    reversal: "If pride inflates ego: wash feet in cold salted water, bow down to earth, recite Surah 55:26."
  },
  {
    id: "discord",
    glyph: "🎭",
    title: "12. Discord & Breaking Conspiracies",
    name: "Ilqa' al-Fitnah (إلقاء الفتنة والعداوة بين الأشرار)",
    category: "Tafriq",
    viability: 94,
    viabilityVerdict: "DESTRUCTIVELY POTENT (94%) — Fixed T-Square (Mercury-Mars-Pluto)",
    gaugeColor: "#7f1d1d",
    astrologicalEngine: "Mercury at 04°13′ Scorpio applying square to Mars at 03°16′ Leo and Pluto at 03°06′ Aquarius (Fixed T-Square).",
    classicalProhibition: "ABSOLUTE WARNING: Only justifiable against a verified conspiracy of persecutors. Casting between righteous individuals brings terrifying karmic ruin.",
    prescribedAction: "Turning a cabal of corrupt corporate, legal, or personal adversaries against one another so they destroy their own plots.",
    authorities: ["Shams al-Ma'arif (Bab al-Baghda' bayna al-Zalamah)", "Picatrix Bk. IV Ch. 4", "PGM VII. 429-458"],
    altarMateria: "Shard of broken earthenware pottery, black ink mixed with gallnut, black candle, rusty iron nails.",
    fumigation: "Sulfur, crushed black mustard seed, assafoetida, dried hot pepper flakes.",
    protocolName: "Protocol 12: Shattering the Conspirators' Council (Tafriq al-Usbah)",
    verse: "وَأَلْقَيْنَا بَيْنَهُمُ الْعَدَاوَةَ وَالْبَغْضَاءَ إِلَىٰ يَوْمِ الْقِيَامَةِ (Surah 5:64)",
    formula: "Write adversaries' names on broken pottery shard separated by letter Zāy (ز) and Khā' (خ). Pass through sulfur smoke. Bury shard at a desolate crossroads. Do not look back.",
    effects: {
      psychological: "Conspirators become instantly suspicious of each other; paranoid infighting and blame games erupt.",
      relational: "The adversarial coalition fractures into hostile factions; former partners sue and expose each other.",
      somatic: "Adversaries suffer chronic headaches, sleep disruption, and nervous tension caused by their own paranoia.",
      astral: "The collective egregor of the conspiracy is shattered into chaotic, competing fragments.",
      karmic: "Turns the weapon of the oppressors back into their own ranks."
    },
    reversal: "Extremely difficult to arrest once ignited. Requires neutral earth burial and formal recitation of verses of peace."
  },
  {
    id: "invisibility",
    glyph: "🌫️",
    title: "13. Invisibility & Psychic Cloaking",
    name: "Al-Ikhfa' & Aphanismos (الإخفاء والحجاب والتعمية عن الأعين)",
    category: "Tahsin",
    viability: 91,
    viabilityVerdict: "HIGHLY COVERT (91%) — 12th House Lunar-Neptunian Shroud",
    gaugeColor: "#64748b",
    astrologicalEngine: "Moon in 12th House (realm of the unseen and cloaked); Neptune Rx in Aries trine Mars (0°29′); Mercury in deep Scorpio.",
    classicalProhibition: "Do not use cloaking to commit fraud, theft, or crime; the veil will dissolve abruptly, exposing you to harsh justice.",
    prescribedAction: "Shielding proprietary trade secrets, camouflaging sensitive communications, psychic invisibility against remote viewing.",
    authorities: ["PGM I. 222-231 (Spell of Invisibility)", "Picatrix Bk. III Ch. 9", "Shams al-Ma'arif (Bab al-Hujub)"],
    altarMateria: "Smoky quartz or grey agate, dark silk cloth, lead token inscribed with the character of Hermes-Thoth.",
    fumigation: "Copal resin, dried fern fronds, poppy seed, frankincense, mugwort.",
    protocolName: "Protocol 13: The Shroud of the Unseen Realm (Hijab al-Ikhfa')",
    verse: "وَجَعَلْنَا مِن بَيْنِ أَيْدِيهِمْ سَدًّا وَمِنْ خَلْفِهِمْ سَدًّا فَأَغْشَيْنَاهُمْ فَهُمْ لَا يُبْصِرُونَ (Surah 36:9)",
    formula: "Wrap smoky quartz and confidential items in dark silk over copal smoke. Recite Surah Ya-Sin verse 9 twenty-one times. Anoint edges with lavender oil.",
    effects: {
      psychological: "Calm, unobtrusive mental state; complete immunity to being noticed or scrutinized in public.",
      relational: "Curious snoops, administrative inspectors, and toxic gossips overlook your presence and paperwork completely.",
      somatic: "Neutralizes somatic stress associated with being watched, targeted, or stalked.",
      astral: "Wraps the auric egg in an astral cloud of neutral grey light that reflects psychic probes back harmlessly.",
      karmic: "Preserves sacred spiritual work until the appointed time of public manifestation."
    },
    reversal: "Remove silk, expose quartz to direct sunlight, recite: 'Let the light reveal what is true.'"
  },
  {
    id: "dreams",
    glyph: "🌙",
    title: "14. Dream Incubation & Oneiromancy",
    name: "Al-Ru'ya & Oneiromanteia (الرؤيا الصالحة واستنزال منام الحق)",
    category: "Kashf",
    viability: 97,
    viabilityVerdict: "SUPREME DREAM TRANSMISSION (97%) — Isis-Sirius Lunar Oracle",
    gaugeColor: "#818cf8",
    astrologicalEngine: "Moon in 12th House (Sleep, Astral Dreams) conjunct Behenian Star Sirius (14°27′); Mercury trine Fomalhaut (Watcher of Visions).",
    classicalProhibition: "Do not consume heavy meats, alcohol, or look at electronic screens immediately before dream incubation rites.",
    prescribedAction: "Receiving clear prophetic guidance, communing with spiritual masters, discovering hidden solutions in sleep.",
    authorities: ["PGM VII. 862-918 (Dream Oracle)", "Picatrix Bk. III Ch. 6 (The Perfect Nature)", "Shams al-Ma'arif (Bab al-Manam)"],
    altarMateria: "Fresh clean white linen pillowcase, virgin parchment, saffron ink, sprig of dried mugwort or wormwood.",
    fumigation: "Frankincense, mugwort, dried lavender, sandalwood.",
    protocolName: "Protocol 14: The Sirius Lucid Oracle (Istikhārah al-Manāmiyyah)",
    verse: "يَا هَادِي يَا خَبِيرُ يَا مُبِينُ (The Guide, The Aware, The Clarifier) — 'Lady Isis-Sirius, grant me an unclouded vision.'",
    formula: "Write single precise question with saffron ink. Anoint corners with lavender. Place paper and mugwort inside pillowcase. Recite formula upon lying down. Keep notebook at bedside.",
    effects: {
      psychological: "High dream recall, spontaneous lucidity, crystalline emotional resolution of waking problems upon waking.",
      relational: "Receives warnings regarding false friends or confirmation of loyal allies prior to mundane events.",
      somatic: "Deep, restorative delta sleep; repair of neurotransmitter exhaustion.",
      astral: "Safe astral travel through the lunar portal directly into the sanctuary of the Higher Self.",
      karmic: "Direct communication with ancestral teachers and spiritual lineage guardians."
    },
    reversal: "Zero backfire; to close dream door upon waking, wash hands, touch cold water, write dream down."
  }
];

console.log(`Loaded all ${allOperativeWorks.length} Grimoiric Operative Works!`);

// Export data
module.exports = { allOperativeWorks };
